### ISSUE TITLE
Dark mode on your website

### ISSUE THREAD

**Issue by jimmywarting** [mozilla/standards-positions#814]
this is not a request for Mozilla Position on an Emerging Web Specification
but a request for https://mozilla.github.io/standards-positions/ to support dark mode.

The site is too bright at night.

and hopefully also make use of `color-scheme` with either of this solutions:

`<meta name="color-scheme" content="dark light">`
```css
@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;
  }
}
```

- https://web.dev/color-scheme/
